### PR TITLE
feat(library/hott) extend equivalences.lean

### PR DESCRIPTION
**Pull request by javra**
add precomposition lemma, use class inference (not entirely sure if this is really desirable in this case)

### CODE REVIEW

**Comment by leodemoura** [comment]
Your changes have been integrated.

**Comment by leodemoura** [comment]
BTW, I performed the merge before you submitted https://github.com/javra/lean/commit/1f81a7e7f4affe132f3c9781f5b5521ac8d4a354

I included my own fix. You should probably replace it with yours because yours looks cleaner.

**Comment by javra** [comment]
Little question about the github workflow, I somehow always manage to screw these things up: (How) can I continue to use the branch from which I made this pull request?

My local "equivalences3" branch is now 2 commits ahead of my local "master" which is the same as "origin/master" (where origin means my github repo) and "upstream master". But my "origin/equivalences3" branch branches away from master much earlier, since I've pulled new commits on my master branch, including my own upstream commits, so I'd have to do something like a rebase for my own github repo...

**Comment by leodemoura** [comment]
To be safe, first save everything you want to save in your own github repository (on your local machine, it is called `origin/master`).
Now, if some disaster happens, you can reset your local master by executing:

```
    git checkout master
    git reset --hard origin/master
```

The `reset` command above forces the current branch to point to the same commit pointed by `origin/master`.

Regarding your question, assuming `blessed/master` is the name of the master branch of `github.com/leanprover/lean.git`. We can integrate things by rebasing your branch with respect to `blessed/master`.

```
     git checkout equivalences3
     git rebase blessed/master
```

This command will put the changes in `equivalences3` on top of whatever is in `blessed/master`.
You may have to solve conflicts if they two branches diverged.
We can also "remove/fix" that last `n` commits by using

```
    git rebase -i HEAD~n
```

This command will open an editor where we can select which commits to squash, edit, ...

Another super-useful command is 

```
    git cherry-pick  <commit-hash>
```

It allows us to pick a commit from a different branch and put on top of the current one.

To integrate your changes I used the following approach:

```
   # create local branch javra
   git checkout -b javra 
   # reset to javra/equivalences3
   git reset --hard javra/equivalences3
   # rebase it with respect to my master
   git rebase master
   # fix conflicts, and compile lean and check if there are problems 
   # ...
   # go back to my master
   git checkout master
   # for it to be local (already integrated) javra
   git reset --hard javra
   # push to blessed
   git push blessed/master
```

**Comment by javra** [comment]
```
git checkout equivalences3
git rebase upstream/master
```

is exactly what I did but then I always run into problems when trying to push to mit github repo rejecting the push saying it is non-fast-forward.

**Comment by javra** [comment]
http://i.imgur.com/JLkKMdp.png

Maybe I also misconfigured something, somehow I feel like origin/equivalences3 should always be behind my local equivalences3...

**Comment by leodemoura** [comment]
To force origin/equivalences3 to be equal to your local equivalences3, you shoud use

```
    git checkout equivalences3
    git push origin +equivalences3
```

The `+` is for a "forced" update. You have to use to sign that you are performing a destructive update, and "rewriting" history.

**Comment by javra** [comment]
Okay thanks, I guess that's the command I was looking for :)

**Pull request closed without merging**
