### PR TITLE
cleaned up notation, introduced basic properties for binary operations, clean up classes for equivalence relations and congruences

### PR DESCRIPTION
**Pull request by avigad**
I invested considerable time cleaning up the classes for equivalence relations and congruences. I have two questions.

(1) Leo, I noticed that you created another "relations" file in the logic directory. I propose merging this with algebra/relation, and moving all the classes (for equivalence and congruence) now in algebra/relation to a new file, algebra/equivalence_relation. Let me know if I should do that.

(2) Right now, to use substitution for iff and other congruence relations, we have to "open relation" to get all the instances. See, for example, logic/examples/instances_test. Should I put all the classes and instances at the top level, so we do not have to do that?

I have a new bug report: with this version of the repository, if I load data/int/basic and introduce an error anywhere in the file (by typing random characters in the middle of an existing proof), Flycheck fails and I get an error message like the one below. Let me know if I should investigate further.

Checker lean-checker returned non-zero exit code 1, but no errors from output: [93/110] generating dep... /home/avigad/projects/lean/library/data/int/flycheck_basic.d                    

[<**main**.FlycheckItem instance at 0xb6de1a8c>, <**main**.FlycheckItem instance at 0xb6de14ec>, <**main**.FlycheckItem instance at 0xb6de142c>, <**main**.FlycheckItem instance at 0xb6de146c>, <**main**.FlycheckItem instance at 0xb6de19ac>, <**main**.FlycheckItem instance at 0xb6de1aac>, <**main**.FlycheckItem instance at 0xb6de1aec>, <**main**.FlycheckItem instance at 0xb6de1b2c>, <**main**.FlycheckItem instance at 0xb6de1b6c>, <**main**.FlycheckItem instance at 0xb6de1bac>, <**main**.FlycheckItem instance at 0xb6de1bec>, <**main**.FlycheckItem instance at 0xb6de1c2c>, <**main**.FlycheckItem instance at 0xb6e2918c>, <**main**.FlycheckItem instance at 0xb6e2908c>, <**main**.FlycheckItem instance at 0xb6e2942c>, <**main**.FlycheckItem instance at 0xb6e2944c>, <**main**.FlycheckItem instance at 0xb6e2930c>, <**main**.FlycheckItem instance at 0xb6e22fac>, <**main**.FlycheckItem instance at 0xb6e2916c>, <**main**.FlycheckItem instance at 0xb6dd26cc>, <**main**.FlycheckItem instance at 0xb6dd260c>, <**main**.FlycheckItem instance at 0xb6dd254c>, <**main**.FlycheckItem instance at 0xb6dd248c>, <**main**.FlycheckItem instance at 0xb6dd23cc>, <**main**.FlycheckItem instance at 0xb6dd232c>, <**main**.FlycheckItem instance at 0xb6dd22ac>, <**main**.FlycheckItem instance at 0xb6dd226c>, <**main**.FlycheckItem instance at 0xb6dd228c>, <**main**.FlycheckItem instance at 0xb6dd252c>, <**main**.FlycheckItem instance at 0xb6dd25cc>, <**main**.FlycheckItem instance at 0xb6dd230c>, <**main**.FlycheckItem instance at 0xb6dd246c>, <**main**.FlycheckItem instance at 0xb6de1c8c>, <**main**.FlycheckItem instance at 0xb6dd250c>, <**main**.FlycheckItem instance at 0xb6dd274c>, <**main**.FlycheckItem instance at 0xb6dd276c>, <**main**.FlycheckItem instance at 0xb6de1cec>, <**main**.FlycheckItem instance at 0xb6de1d2c>, <**main**.FlycheckItem instance at 0xb6de1e0c>, <**main**.FlycheckItem instance at 0xb6de1e4c>, <**main**.FlycheckItem instance at 0xb6de1d6c>, <**main**.FlycheckItem instance at 0xb6de1dac>, <**main**.FlycheckItem instance at 0xb6de1dec>, <**main**.FlycheckItem instance at 0xb6de1eac>, <**main**.FlycheckItem instance at 0xb6de1eec>, <**main**.FlycheckItem instance at 0xb6de1f2c>, <**main**.FlycheckItem instance at 0xb6de1f6c>, <**main**.FlycheckItem instance at 0xb6de1fac>, <**main**.FlycheckItem instance at 0xb6de1fec>, <**main**.FlycheckItem instance at 0xb6de1c6c>, <**main**.FlycheckItem instance at 0xb6e0608c>, <**main**.FlycheckItem instance at 0xb6e060cc>, <**main**.FlycheckItem instance at 0xb6e0610c>, <**main**.FlycheckItem instance at 0xb6e0614c>, <**main**.FlycheckItem instance at 0xb6e0618c>, <**main**.FlycheckItem instance at 0xb6e061cc>, <**main**.FlycheckItem instance at 0xb6e0620c>, <**main**.FlycheckItem instance at 0xb6e0624c>, <**main**.FlycheckItem instance at 0xb6e0628c>, <**main**.FlycheckItem instance at 0xb6e062cc>, <**main**.FlycheckItem instance at 0xb6e0630c>, <**main**.FlycheckItem instance at 0xb6e0634c>, <**main**.FlycheckItem instance at 0xb6e0638c>, <**main**.FlycheckItem instance at 0xb6e063cc>, <**main**.FlycheckItem instance at 0xb6e0640c>, <**main**.FlycheckItem instance at 0xb6e0644c>, <**main**.FlycheckItem instance at 0xb6e0648c>, <**main**.FlycheckItem instance at 0xb6e064cc>, <**main**.FlycheckItem instance at 0xb6e0650c>, <**main**.FlycheckItem instance at 0xb6e0654c>, <**main**.FlycheckItem instance at 0xb6e0658c>, <**main**.FlycheckItem instance at 0xb6e065cc>, <**main**.FlycheckItem instance at 0xb6e0660c>, <**main**.FlycheckItem instance at 0xb6e0664c>, <**main**.FlycheckItem instance at 0xb6e0668c>, <**main**.FlycheckItem instance at 0xb6e066cc>, <**main**.FlycheckItem instance at 0xb6e067ac>, <**main**.FlycheckItem instance at 0xb6e067ec>, <**main**.FlycheckItem instance at 0xb6e0670c>, <**main**.FlycheckItem instance at 0xb6e0674c>, <**main**.FlycheckItem instance at 0xb6e068ec>, <**main**.FlycheckItem instance at 0xb6e0678c>, <**main**.FlycheckItem instance at 0xb6e068ac>, <**main**.FlycheckItem instance at 0xb6e0684c>, <**main**.FlycheckItem instance at 0xb6e0688c>, <**main**.FlycheckItem instance at 0xb6e0694c>, <**main**.FlycheckItem instance at 0xb6e0698c>, <**main**.FlycheckItem instance at 0xb6e069cc>, <**main**.FlycheckItem instance at 0xb6e06a0c>, <**main**.FlycheckItem instance at 0xb6e06a4c>, <**main**.FlycheckItem instance at 0xb6e06a8c>, <**main**.FlycheckItem instance at 0xb6e06b6c>, <**main**.FlycheckItem instance at 0xb6e06acc>, <**main**.FlycheckItem instance at 0xb6e06b0c>, <**main**.FlycheckItem instance at 0xb6e06b4c>, <**main**.FlycheckItem instance at 0xb6e06c6c>, <**main**.FlycheckItem instance at 0xb6e06bcc>, <**main**.FlycheckItem instance at 0xb6e06cec>, <**main**.FlycheckItem instance at 0xb6e06c0c>, <**main**.FlycheckItem instance at 0xb6e06dac>, <**main**.FlycheckItem instance at 0xb6dd2d0c>]

Checker definition probably flawed.

### CODE REVIEW

**Comment by leodemoura** [comment]
> (1) Leo, I noticed that you created another "relations" file in the logic directory. I propose merging this with algebra/relation, and moving all the classes (for equivalence and congruence) now in algebra/relation to a new file, algebra/equivalence_relation. Let me know if I should do that.

This is another instance of "the definitions must be in the environment as soon as possible".
I need them for the well founded relation module, and the well founded relation module is needed by the definitional package.

**Comment by avigad** [comment]
But is there any reason why they cannot be algebra/relation? We can make
that file contain only definitions of general properties of relations, and
nothing else.

**Comment by leodemoura** [comment]
> But is there any reason why they cannot be algebra/relation?

Some declarations (like the ones in logic/relation) are used to initialize the system.
It is nice to have them in a single place. For me, they are independent of the `algebra` module.
Another reason is that the definitions in `algebra` are not the ones I want. They go to `Type` instead of `Prop`. Another reason is that it contains definitions that I don't want loaded when initializing the system. 

I have been thinking about renaming `logic` folder to `init` like Coq, and have all the initialization modules grouped in a single place. Moreover, the init modules should be loaded automatically.
Otherwise the user will get really unexpected behavior (e.g., `no_confusion` is not generated if `eq` and `heq` are not already in the environment). 
Right now, the initialization is a mess. We read files from `logic`, `data`, `tools` and `algebra`.

Another motivation for having `init` is that it would be clear what cannot be "freely changed". I say a library file cannot be freely changed if it would affect the C++ executable. Example: we cannot rename `prod` without breaking the code that generates `below`. We cannot rename `eq` and `heq` without breaking the code that generates `no_confusion`, etc.

**Comment by avigad** [comment]
This sounds like a good idea. I will leave it to you. As always, let me
know if there is something I can do to help.

On Fri, Nov 28, 2014 at 3:10 PM, Leonardo de Moura <notifications@github.com

**Pull request closed without merging**
