### PR TITLE
add vector and category

### PR DESCRIPTION
**Pull request by fpvandoorn**
Here are my current versions of category.lean and vector.lean. There isn't much in either, but it's a start. It compiles with the current version, so it's updated to use "open" and "." (instead of "include" and "_"). It does use some superfluous sorry's and check's

### CODE REVIEW

**Comment by leodemoura** [comment]
I reorganized the commits (reason: some of them would not work when moved to the top of the commit stack). I also made minor edits (e.g., added Copyright, indented declarations inside of namespace). Here is the result:
https://github.com/leodemoura/lean/commits/floris

If you agree with the changes I will merge them in the blessed repository.

**Comment by leodemoura** [comment]
BTW, I also deleted the Coq code in comments.

**Comment by fpvandoorn** [comment]
Ok, that's fine. Thanks!

**Comment by leodemoura** [comment]
The commit has been integrated.

**Pull request closed without merging**
